---
- name: extract zipped backend
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: 'run node application'
  become: yes
  shell: |
    cd /home/ubuntu
    # mkdir app
    # mv artifact.tar.gz app/artifact.tar.gz
    # cd app
    tar xzvf artifact.tar.gz
    npm i 
    npm run build
    pm2 stop default
    pm2 start npm -- start